GET http://127.0.0.1:4000/product-api/products
###

GET http://127.0.0.1:4000/product-api/products-name/maggi
###

POST http://127.0.0.1:4000/product-api/products
Content-Type: application/json

{
    "id":11,
    "name":"maggi",
    "price":25,
    "brand":"nestle"
}
###